FROM golang:1.11-alpine

# Install git
RUN apk add --no-cache git

# Copy Repository
WORKDIR /home/root/go/src/github.com/george-e-shaw-iv/integration-tests-example/
COPY . ./

# Run tests
CMD CGO_ENABLED=0 go test ./...