FROM golang:1.12-alpine

# Install git
RUN set -ex; \
    apk update; \
    apk add --no-cache git

# Set working directory
WORKDIR /go/src/github.com/george-e-shaw-iv/integration-tests-example/

# Run tests
CMD CGO_ENABLED=0 go test ./...